language: ruby
rvm:
  - "2.1.0"
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database uw_ruby_cert;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
bundler_args:
  --binstubs=./bundler_stubs
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aec44acc314a2ba1bcc6
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
#Pre-20140422
#language: ruby
#rvm:
#- 2.1.0
##deploy:
##  provider: heroku
##  api_key:
##    secure: c52daf6e-4a9c-491b-a38e-331793d2fdda
##  app: dbaynes-portfolio
#script: bundle exec rake db:migrate 

